name: Deploy ECS Fargate

permissions:
  id-token: write
  contents: read

on:
#   push:
#     branches:
#       - main  
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Selecionar o ambiente'
        required: true
        default: 'hom'
        type: choice
        options:
          - dev
          - hom
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1      

    - name: Terraform init
      run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"
      working-directory: ./terraform

    - name: Terraform Create Workspace if Not Exists
      run: |
        terraform workspace list | grep ${{ github.event.inputs.workspace }} || terraform workspace new ${{ github.event.inputs.workspace }}
      working-directory: ./terraform

    - name: Terraform Select Workspace
      run: terraform workspace select ${{ github.event.inputs.workspace }}
      working-directory: ./terraform

    - name: Terraform Plan
      run: |
        if [ "${{ github.event.inputs.workspace }}" == "hom" ]; then
          terraform plan -var-file="hom.tfvars"
        elif [ "${{ github.event.inputs.workspace }}" == "prod" ]; then
          terraform plan -var-file="prod.tfvars"
        else
          terraform plan
        fi
      working-directory: ./terraform

    - name: Terraform Apply
      run: |
        if [ "${{ github.event.inputs.workspace }}" == "hom" ]; then
          terraform apply -var-file="hom.tfvars" -auto-approve
        elif [ "${{ github.event.inputs.workspace }}" == "prod" ]; then
          terraform apply -var-file="prod.tfvars" -auto-approve
        else
          terraform apply -auto-approve
        fi
      working-directory: ./terraform

    - name: Terraform Workspace Output
      run: terraform output
      working-directory: ./terraform
