name: Destroy Terraform Infrastructure
permissions:
  id-token: write
  contents: read
  
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - hom
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}    
    permissions:
        id-token: write
        contents: read  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1      

    - name: Terraform init
      run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"
      working-directory: ./terraform

    - name: Terraform Create Workspace if Not Exists
      run: |
        terraform workspace list | grep ${{ github.event.inputs.environment }} || terraform workspace new ${{ github.event.inputs.environment }}
      working-directory: ./terraform

    - name: Terraform Select Workspace
      run: terraform workspace select ${{ github.event.inputs.environment }}
      working-directory: ./terraform

    - name: Terraform Destroy
      run: |
        if [ "${{ github.event.inputs.environment }}" == "hom" ]; then
          terraform destroy -var-file="hom.tfvars" -auto-approve
        elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
          terraform destroy -var-file="prod.tfvars" -auto-approve
        else
          terraform destroy -auto-approve
        fi
      working-directory: ./terraform
